name: release
on:
  workflow_dispatch:

env:
  GRAALVM_TAG: ol9-java17-22.3.0
  RELEASE_REPO: observabilitystack/graalvm-maven-builder

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3

      - name: build Docker file
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/arm64, linux/amd64
          tags: |
            ghcr.io/${env.RELEASE_REPO}:${{ env.GRAALVM_TAG }}
            ${env.RELEASE_REPO}:${{ env.GRAALVM_TAG }}
