name: release
on:
  workflow_dispatch:

jobs:
  release:
    strategy:
      matrix:
        graalvm_tag: [21.0.2-ol9, 22.0.2-ol9, 25.0.0-ol10] # 25.0.0-muslib-ol10
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4

      - name: build Docker file
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/arm64, linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}:${{ matrix.graalvm_tag }}
            ${{ github.repository }}:${{ matrix.graalvm_tag }}
          build-args: |
            GRAALVM_TAG=${{ matrix.graalvm_tag }}
